openapi: 3.0.2
info:
  title: AutoML
  description: | 
    We are designing the AutoML platform that would make it easy for non-technical people to build custom AI solutions and AI-powered process automation.
    
    Please copy the entire content of this doc to the swagger editor (https://editor.swagger.io) to design the API
    
    Reference: [API design for JSON HTTP APIs](https://cloud.google.com/apis/design/errors) [error codes for RPC APIs](https://github.com/googleapis/googleapis/blob/master/google/rpc/code.proto)
  termsOfService: https://automl.com/terms/
  contact:
    name: API Support
    url: https://automl.com/support/
    email: support@automl.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: v1beta1
servers:
- url: https://automl.com/v1beta1
  description: Supports latest preview features.
- url: https://automl.com/v1
  description: Stable
security:
  - oauth2:
      - self
tags:
- name: Authorization
  description: Authentication and Authorization
- name: Namespace
  description: provides namespace level isolation
- name: Role
  description: Roles can be defined or modified in the configuration file as a list of dictionaries.
- name: User
- name: Group
- name: Dataset
- name: Model
- name: TrainingJob
- name: Evaluation
- name: BatchPredictionJob
- name: Endpoint
- name: Operation
- name: Experiment
- name: Run
- name: Datastore
paths:
  /oauth2/authorize:
    get:
      tags:
      - Authorization
      summary: OAuth 2.0 authorize endpoint
      description: |
        Redirect users to this URL to begin the OAuth process.
        It is not an API endpoint.
    post:
      tags:
      - Authorization
      summary: The OAuth server authenticates the user
      description: The OAuth server will render a login form to gather login information, such as a username and password, then the user can enter credentials and the OAuth server authenticates the user.
      operationId: login
  /oauth2/token:
    post:
      tags:
      - Authorization
      summary: Request an OAuth2 token
      description: |
        Request an OAuth2 token from an authorization code "Client credential grant type".
        This request completes the OAuth process.
  /namespaces/{namespace}:
    put:
      operationId: putNamespace
      summary: Create a namespace
      description: Creates a new namespace object. A namespace enables the contextual grouping of related jobs and datasets. Namespaces must contain only letters (`a-z`, `A-Z`), numbers (`0-9`), underscores (`_`), dashes (`-`), colons (`:`), slashes (`/`), or dots (`.`). A namespace is case-insensitive with a maximum length of `1024` characters. Note jobs and datasets will be unique within a namespace, but not across namespaces.
      tags:
        - Namespace
    get:
      operationId: getNamespace
      summary: Retrieve a namespace
      description: Returns a namespace.
      tags:
        - Namespace
  /namespaces:
    get:
      operationId: getNamespaces
      summary: List all namespaces
      description: Returns a list of namespaces.
      tags:
        - Namespace
  /roles:
    get:
      tags:
      - Role
      summary: List roles
      security: []
  /user:
    get:
      tags:
      - User
      summary: Return authenticated user's model
      security:
        - oauth2:
            - read:users
            - read:users:name
            - read:users:groups
            - read:roles:users
            - admin:auth_state
  /users:
    get:
      tags:
      - User
      summary: List users
      security:
        - oauth2:
            - read:users
            - read:users:name
            - read:users:groups
            - read:roles:users
            - admin:auth_state
    post:
      tags:
      - User
      summary: Create multiple users
      security:
        - oauth2:
            - admin:users
  /users/{user}:
    get:
      tags:
      - User
      summary: Get a user by user id
      security:
        - oauth2:
            - read:users
            - read:users:name
            - read:users:groups
            - read:roles:users
            - admin:auth_state
    delete:
      tags:
      - User
      summary: Delete a user
      security:
        - oauth2:
            - admin:users
    patch:
      tags:
      - User
      summary: Modify a user
      description: Change a user's name or admin status
      security:
        - oauth2:
            - admin:users
  /groups:
    get:
      tags:
      - Group
      summary: List groups
      security:
        - oauth2:
            - read:groups
            - read:groups:name
            - read:roles:groups
    post:
      tags:
      - Group
      summary: Create a group
      security:
        - oauth2:
            - admin:groups
  /groups/{group}:
    get:
      tags:
      - Group
      summary: Get a group 
      security:
        - oauth2:
            - read:groups
            - read:groups:name
            - read:roles:groups
    delete:
      tags:
      - Group
      summary: Delete a group
      security:
        - oauth2:
            - admin:groups
  /groups/{group}/users:
    post:
      tags:
      - Group
      summary: Add users to a group
      security:
        - oauth2:
            - groups
    delete:
      tags:
      - Group
      summary: |
        Remove users from a group
      description: |
        Body should be a JSON dictionary
        where `users` is a list of usernames to remove from the groups.

        ```json
        {
          "users": ["name1", "name2"]
        }
        ```
      security:
        - oauth2:
            - groups
  /namespaces/{namespace}/files/{filename}:
    post:
      tags:
      - Dataset
      summary: upload files
      operationId: automl.namespaces.files.create
  /namespaces/{namespace}/datasets:
    post:
      tags:
      - Dataset
      summary: Creates a dataset
      description: Tabular training data in MinIO Storage is not imported into platform. (When you import from local files, they are imported into MinIO Storage.) When you create a dataset with tabular data, the data is associated with the dataset. Changes you make to your data source in MinIO Storage after dataset creation are incorporated into models subsequently trained with that dataset. A snapshot of the dataset is taken when model training begins.
      operationId: automl.namespaces.datasets.create
    get:
      tags:
      - Dataset
      description: Lists datasets in the namespace.
      operationId: automl.namespaces.datasets.list
  /namespaces/{namespace}/datasets/{dataset}:
    get:
      operationId: getDataset
      summary: Retrieve a dataset
      description: Returns a dataset.
      tags:
        - Dataset
    delete:
      tags:
      - Dataset
      summary: Delete Dataset by Dataset Id
      operationId: delete_dataset_by_id
    patch:
      tags:
      - Dataset
      summary: Modify a dataset
      operationId: patch_dataset_by_id
  /namespaces/{namespace}/datasets/{dataset}/tableSpecs:
    get:
      tags:
      - Dataset
      description: Lists table specs in a dataset.
      operationId: automl.namespaces.datasets.tableSpecs.list
  /namespaces/{namespace}/datasets/{dataset}/tableSpecs/{tableSpec}/columnSpecs:
    get:
      tags:
      - Dataset
      description: Lists column specs in a table spec.
      operationId: automl.projects.locations.datasets.tableSpecs.columnSpecs.list
  /namespaces/{namespace}/datasets/{dataset}/annotationSpecs/{annotationSpec}:
    get:
      operationId: automl.namespaces.datasets.annotationSpecs.get
      description: Gets an AnnotationSpec.
      tags:
        - Dataset
  /namespaces/{namespace}/models:
    get:
      tags:
      - Model
      description: Lists models in the namespace.
      operationId: automl.namespaces.models.list
    post:
      tags:
      - Model
      description: Creates a model which will later contain one or more versions
      operationId: automl.namespaces.models.create
  /namespaces/{namespace}/models/{model}:
    get:
      operationId: automl.namespaces.models.get
      summary: Retrieve a model
      description: Returns a model.
      tags:
        - Model
    patch:
      tags:
      - Model
      summary: Modify a model
      operationId: patch_model_by_id
  /namespaces/{namespace}/models/{model}/versions:
    get:
      tags:
      - Model
      description: Lists versions
      operationId: automl.namespaces.models.versions.list
    post:
      tags:
      - Model
      description: Creates a new version of a model
      operationId: automl.namespaces.models.versions.create
  /namespaces/{namespace}/models/{model}/versions/{version}:
    get:
      operationId: automl.namespaces.models.versions.get
      summary: Retrieve a version
      description: Returns a version.
      tags:
        - Model
    patch:
      tags:
      - Model
      summary: Modify a version
      operationId: automl.namespaces.models.versions.patch
    delete:
      tags:
      - Model
      summary: Delete version
      operationId: automl.namespaces.models.versions.delete
  /namespaces/{namespace}/trainingJob:
    post:
      tags:
      - TrainingJob
      description: Creates a TrainingJob. A created TrainingJob right away will be attempted to be run. When you train a model, several model evaluations are created for it, a summary evaluation, and one evaluation for each annotation.
      operationId: automl.namespaces.trainingJob.create
  /namespaces/{namespace}/trainingJob/{job}:
    get:
      tags:
      - TrainingJob
      description: Gets a TrainingJob
      operationId: automl.namespaces.trainingJob.get
  /namespaces/{namespace}/models/{model}/versions/{version}/evaluations:
    get:
      tags:
        - Evaluation
      description: Lists model evaluations.
      operationId: automl.projects.locations.models.version.evaluations.list
  /namespaces/{namespace}/models/{model}/versions/{version}/evaluations/{evaluation}/slices:
    get:
      tags:
        - Evaluation
      description: Lists ModelEvaluationSlices in a ModelEvaluation. Tabular forecasting models do not have evaluation metric slices. Tabular regression models do not have evaluation metric slices.
      operationId: automl.projects.locations.models.version.evaluations.slices.list
  /namespaces/{namespace}/batchPredictionJobs:
    post:
      tags:
      - BatchPredictionJob
      description: Creates a batchPredictionJobs.
  /namespaces/{namespace}/batchPredictionJob/{job}:
    get:
      tags:
      - BatchPredictionJob
      description: Gets a batchPredictionJob
      operationId: automl.namespaces.batchPredictionJob.get
  /namespaces/{namespace}/endpoints:
    post:
      tags:
      - Endpoint
      description: Creates an Endpoint, If successful, the response body contains a newly created instance of Operation.
      operationId: automl.namespaces.endpoints.create
    get:
      tags:
      - Endpoint
      description: Lists endpoints in the namespace.
      operationId: automl.namespaces.endpoints.list
  /namespaces/{namespace}/endpoints/{endpoint}:
    delete:
      tags:
      - Endpoint
      description: Deletes an Endpoint.
      operationId: automl.namespaces.endpoints.delete
  /namespaces/{namespace}/endpoints/{endpoint}/predict:
    post:
      tags:
      - Endpoint
      description: Perform an online prediction.
      operationId: automl.namespaces.endpoints.predict
  /namespaces/{namespace}/operations/{operation}:
    get:
      description: Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.
      operationId: automl.namespaces.operations.get
      tags:
        - Operation
  /namespaces/{namespace}/operations/{operation}/cancel:
    post:
      description: Starts asynchronous cancellation on a long-running operation. The server makes a best effort to cancel the operation, but success is not guaranteed. If the server doesn't support this method, it returns Code.UNIMPLEMENTED. Clients can use Operations.GetOperation or other methods to check whether the cancellation succeeded or whether the operation completed despite cancellation. On successful cancellation, the operation is not deleted; instead, it becomes an operation with an O[...]
      operationId: automl.namespaces.operations.cancel
      tags:
        - Operation
  /namespaces/{namespace}/experiments:
    get:
      tags:
        - Experiment
      description: Finds all experiments.
      operationId: automl.namespaces.experiments.get
  /namespaces/{namespace}/runs:
    get:
      tags:
        - Run
      description: Finds all runs. An experiment will typically contain multiple runs. A run can have zero or more child runs.
      operationId: automl.namespaces.runs.get
components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://hub.example/hub/api/oauth2/authorize
          tokenUrl: https://hub.example/hub/api/oauth2/token
          scopes:
            (openapi-reference): https://github.com/jupyterhub/jupyterhub/blob/main/docs/source/_static/rest-api.yml
            (rbac-reference): https://jupyterhub.readthedocs.io/en/stable/rbac/index.html
            (scope-reference): https://jupyterhub.readthedocs.io/en/stable/rbac/scopes.html
            self:
              The user’s own resources
            all:
              Contains all available scopes and grants full rights to all actions.
            admin:users:
              Read, write, create and delete users and their authentication
              state.
            admin:auth_state: Read a user’s authentication state.
            users:
              Read and write permissions to user models (excluding authentication state).
            delete:users: Delete users.
            list:users: List users, including at least their names.
            read:users:
              Read user models (excluding authentication state).
            read:users:name: Read names of users.
            read:users:groups: Read users’ group membership.
            read:roles: Read role assignments.
            read:roles:users: Read user role assignments.
            read:roles:groups: Read group role assignments.
            admin:groups: Read and write group information, create and delete groups.
            groups: Read and write group information, including adding/removing users
              to/from groups.
            list:groups: List groups, including at least their names.
            read:groups: Read group models.
            read:groups:name: Read group names.
            delete:groups: Delete groups.
            read:metrics: Read prometheus metrics.
